version: "3"
services:
  controller:
    image: jianshao/fastchat-demo:${image_ver}
    container_name: ${container_name_prefix}controller
    restart: unless-stopped
    command:
      - python
      - -m
      - fastchat.serve.controller
      - --host
      - 0.0.0.0
  en-embed-worker:
    image: jianshao/fastchat-demo:${image_ver}
    container_name: ${container_name_prefix}en-embed-worker
    restart: unless-stopped
    depends_on:
      - controller
    command:
      - python
      - -m
      - fastchat.serve.model_worker
      - --host
      - 0.0.0.0
      - --controller-address
      - http://controller:21001
      - --worker-address
      - http://en-embed-worker:21002
      - --model-path
      - ${en_embed_model_path}
      - --model-names
      - ${en_embed_model_name}
    volumes:
      - ${model_cache_path}:/home/devel/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
  zh-embed-worker:
    image: jianshao/fastchat-demo:${image_ver}
    container_name: ${container_name_prefix}zh-embed-worker
    restart: unless-stopped
    depends_on:
      - controller
    command:
      - python
      - -m
      - fastchat.serve.model_worker
      - --host
      - 0.0.0.0
      - --controller-address
      - http://controller:21001
      - --worker-address
      - http://zh-embed-worker:21002
      - --model-path
      - ${zh_embed_model_path}
      - --model-names
      - ${zh_embed_model_name}
    volumes:
      - ${model_cache_path}:/home/devel/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
  chat-worker:
    image: jianshao/fastchat-demo:${image_ver}
    container_name: ${container_name_prefix}chat-worker
    restart: unless-stopped
    depends_on:
      - controller
    command:
      - python
      - -m
      - fastchat.serve.model_worker
      # - --load-8bit
      - --host
      - 0.0.0.0
      - --controller-address
      - http://controller:21001
      - --worker-address
      - http://chat-worker:21002
      - --model-names
      - ${chat_model_name}
      - --model-path
      - ${chat_model_path}
    volumes:
      - ${model_cache_path}:/home/devel/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
  openai:
    image: jianshao/fastchat-demo:${image_ver}
    container_name: ${container_name_prefix}openai
    restart: unless-stopped
    command:
      - python
      - -m
      - fastchat.serve.openai_api_server
      - --host
      - 0.0.0.0
      - --controller-address
      - http://controller:21001
    ports:
      - 8000:8000
  nextchat:
    image: yidadaa/chatgpt-next-web:v2.11.3
    container_name: ${container_name_prefix}nextchat
    restart: unless-stopped
    depends_on:
      - openai
    environment:
      - BASE_URL=http://openai:8000
    ports:
      - 3000:3000
