version: "3"
services:
  openai:
    image: jianshao/llama-cpp-demo:${image_ver}
    container_name: ${container_name_prefix}openai
    restart: unless-stopped
    environment:
      - HF_REPO_ID=abetlen/replit-code-v1_5-3b-GGUF
      - HF_MODEL_FILE=replit-code-v1_5-3b.Q4_0.gguf
      - HF_MODEL_ALIAS=replit-code-v1_5-3b
      - "LC_ARGS=--n_ctx 16192"
    volumes:
      - ${model_cache_path}:/home/devel/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
